//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTFUL
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public int idcaja { get; set; }
        public int idsucursal { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> idempleado { get; set; }
        public Nullable<int> efectivo { get; set; }
        public int tipo { get; set; }
    
        public virtual cajasxsucursal cajasxsucursal { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
