//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTFUL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gspEntity : DbContext
    {
        public gspEntity()
            : base("name=gspEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<empleadosxsucursal> empleadosxsucursals { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<productosxsucursal> productosxsucursals { get; set; }
        public virtual DbSet<proveedore> proveedores { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sucursale> sucursales { get; set; }
        public virtual DbSet<tipopago> tipopagoes { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<cajasxsucursal> cajasxsucursals { get; set; }
        public virtual DbSet<caja> cajas { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
    }
}
