//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTFUL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleadosxsucursal
    {
        public int idempleado { get; set; }
        public int idsucursal { get; set; }
        public int idrol { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual role role { get; set; }
        public virtual sucursale sucursale { get; set; }
    }
}
